import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Playfair_Display, DM_Sans } from "next/font/google";
const playfair = Playfair_Display({ subsets: ["latin"], variable: "--font-serif" });
const dmSans = DM_Sans({ subsets: ["latin"], variable: "--font-sans" });

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600'], display: "swap" })

export const metadata = {
  title: "Travel Guide website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"

    >
      <body className={`${poppins.className} w-screen h-screen bg-black`}><Navbar />{children}</body>
    </html>
  );
}
